if has('gui_running')
   set guifont=Iosevka
endif

set expandtab

" open NERDTree automatically if no file specified
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" open NERDTree on Ctrl-n
map <C-n> :NERDTreeToggle<CR>
